### ISSUE TITLE
分配工作

### ISSUE THREAD

**Issue by Andrewyg** [Andrew-Source/School-Science-Research#2]
請在以下留言，討論工作分配。

  - [x] 前台
  - [x] 後台
  - [x] 設計
  - [x] 分析

**Comment by popcorn-volcano** [comment]
- [x]  前台
  - 楊振國
  - 蔡牧翰
- [x]  後台
  - 楊記綱
- [x]  設計
  - 楊記綱
  - 蔡牧翰
  - 楊振國
- [x]  分析
  - 蔡牧翰

**Comment by Andrewyg** [comment]
目前暫定這樣。
